server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
    gcp:
      credentials:
        location: classpath:gcpkey.json
      project-id: ${spring.gcp.storage.credentials.project-id}

  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        logger-level: FULL
  httpclient:
    enabled: true

purchase:
  root: http://localhost:8081
  post: /v1/purchases


game:
  root: http://localhost:8083
  post: /v1/games

block:
  root: http://localhost:8080
  post: /v1/blocks

