server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

spring:
  application:
    name: member-service

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${spring.datasource.master.jdbc-url}
      username: ${spring.datasource.master.username}
      password: ${spring.datasource.master.password}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${spring.datasource.slave.jdbc-url}
      username: ${spring.datasource.slave.username}
      password: ${spring.datasource.slave.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
    gcp:
      credentials:
        location: classpath:gcpkey.json
      project-id: ${spring.gcp.storage.credentials.project-id}

  kafka:
    bootstrapAddress: ${spring.kafka.bootstrapAddress}
    interestTopic: interestCount
    ratingTopic: rating
    commentTopic: commentCount

  main:
    allow-bean-definition-overriding: true

  session:
    store-type: redis

  redis:
    host: host.docker.internal
    port: 6379

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        logger-level: FULL
  httpclient:
    enabled: true
