server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
    gcp:
      storage:
        credentials:
          location: file:/home/404notbad404/envfile/gcpstorage.json
        project-id: ${spring.gcp.storage.credentials.project-id}

  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        logger-level: FULL
  httpclient:
    enabled: true

purchase:
  post: /purchase-service/v1/purchases


block:
  post: /block-service/v1/blocks